server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Rahul@123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

eureka:

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka

management:

  endpoints:

    web:

      exposure:

        include: "*"

jwt:
  secret: 8Qe6fXz2K9mN5pR1vT7yU3aB8dE4gH6jL0nP2sW9xY5zC1vM7qR4tF8kN6dA3hJ
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
